import * as THREE from 'https://unpkg.com/three@0.160.0/build/three.module.js';

const state={lang:'zh',scene:'home',dataMode:false,galleries:{poster:0,video:0}};
const T={zh:{brand:'陈思睿 / CELESTE',home:'首页',contact:'联系方式',heroTitle:'把数据、研究与视觉<br/>编织成可感知的叙事。',dataDesc:'研究、分析与交互可视化',poster:'海报 / 长图',posterDesc:'视觉系统与信息设计',video:'视频 / 动态',videoDesc:'剪辑、渲染与动态图像',about:'关于我',aboutDesc:'经历、技能与方法',dialect:'中国方言声学地图',jstor:'JSTOR 中文用户研究',dataNews:'预制菜数据新闻',backOrbit:'返回主轨道',posterTitle:'海报与长图',posterIntro:'统一裁切的视觉档案。拖动、滚轮或按钮均可浏览，点击作品展开完整信息。',videoTitle:'视频与动态视觉',videoIntro:'新闻影像、MMD渲染与短视频实验。点击卡片进入沉浸式播放界面。',backHome:'返回首页',aboutTitle:'研究复杂问题，<br/>并让答案清晰可见。',aboutP1:'伦敦国王学院数字人文硕士，关注数据分析、用户研究、计算方法与视觉传播之间的交叉地带。',aboutP2:'我的工作从采访和定性编码开始，也可能从一组音频、一个内容账号或一张空白画布开始。最终目标始终相同：发现结构，解释证据，构建可理解的体验。',role:'角色',tools:'工具',year:'年份'},en:{brand:'CELESTE CHEN',home:'HOME',contact:'CONTACT',heroTitle:'Turning data, research<br/>and visuals into felt stories.',dataDesc:'Research, analysis & interactive visuals',poster:'POSTER / EDITORIAL',posterDesc:'Visual systems & information design',video:'VIDEO / MOTION',videoDesc:'Editing, rendering & moving image',about:'ABOUT',aboutDesc:'Experience, skills & methods',dialect:'Dialect Acoustic Atlas',jstor:'JSTOR Chinese UX Research',dataNews:'Prepared Food Data Story',backOrbit:'RETURN TO ORBIT',posterTitle:'Posters & Editorial',posterIntro:'A consistently cropped visual archive. Drag, scroll or use arrows; click any work to expand.',videoTitle:'Video & Moving Image',videoIntro:'News films, MMD renders and short-form experiments in an immersive viewing system.',backHome:'BACK HOME',aboutTitle:'Researching complexity,<br/>then making it visible.',aboutP1:'Digital Humanities MA at King’s College London, working across data analysis, user research, computational methods and visual communication.',aboutP2:'A project may begin with interviews and qualitative codes, a collection of audio, a content account or an empty canvas. The goal remains the same: find structure, interpret evidence and build an understandable experience.',role:'ROLE',tools:'TOOLS',year:'YEAR'}};

const posters=[
['程序员节活动长图','Programmer’s Day Editorial','2024','VIS-01','视觉设计 / 长图排版','Visual design / editorial layout','Photoshop · Illustrator','#ded8cf','linear-gradient(135deg,transparent 20%,#ff4a2a 20% 34%,transparent 34%),radial-gradient(circle at 72% 22%,#111 0 12%,transparent 12.5%)'],
['减重训练营活动视觉','Wellness Campaign System','2024','VIS-02','活动视觉 / 信息设计','Campaign visual / information design','Photoshop · Canva','#e4e8db','repeating-linear-gradient(0deg,transparent 0 28px,rgba(20,40,24,.18) 28px 29px),linear-gradient(115deg,#a5d86c 0 32%,transparent 32%)'],
['小红书模板系统','RED Content Template System','2023','VIS-03','内容设计 / 模板规范','Content design / template system','Photoshop · Figma','#f1c9d3','linear-gradient(30deg,transparent 45%,#fa335c 45% 54%,transparent 54%),repeating-linear-gradient(90deg,rgba(255,255,255,.65) 0 12px,transparent 12px 24px)'],
['校庆纪念视觉','Anniversary Visual Identity','2023','VIS-04','概念设计 / 物料制作','Concept / collateral design','Photoshop · Illustrator','#e7dfce','radial-gradient(circle at 50% 42%,transparent 0 18%,#7b1123 18.5% 20%,transparent 20.5%)'],
['活动招募信息长图','Volunteer Recruitment Story','2022','VIS-05','推文排版 / 封面设计','Editorial layout / cover','Photoshop · WeChat Editor','#dce5ec','linear-gradient(155deg,transparent 0 24%,#315b7d 24% 38%,transparent 38%)'],
['海报实验合集','Poster Experiments','2022–25','VIS-06','视觉实验','Visual experimentation','Photoshop · Blender','#d5d2e8','conic-gradient(from 45deg at 50% 50%,#342466 0 12%,transparent 12% 25%,#fe7d41 25% 37%,transparent 37% 50%,#342466 50% 62%,transparent 62%)']
].map(x=>({title:[x[0],x[1]],year:x[2],code:x[3],role:[x[4],x[5]],tools:x[6],bg:x[7],pattern:x[8],desc:['项目详情将在替换真实作品后补充。','Detailed case-study text will be added with the final artwork.'],tags:['Visual','Editorial','System']}));
const videos=[
['中非木雕故事','Woodcarving Across Borders','2024','MOV-01','拍摄 / 剪辑','Cinematography / editing','Premiere Pro · Camera','#0b0c0f','radial-gradient(circle at 60% 45%,rgba(239,72,38,.75),transparent 18%),linear-gradient(105deg,transparent 15%,rgba(230,205,164,.36) 15% 32%,transparent 32%)'],
['竹编耳饰文化体验','Bamboo Weaving Experience','2024','MOV-02','拍摄 / 后期','Cinematography / post-production','Premiere Pro','#0b100b','repeating-linear-gradient(25deg,rgba(148,178,80,.35) 0 5px,transparent 5px 22px)'],
['智慧农业宣传影像','Smart Agriculture Film','2024','MOV-03','现场支持 / 剪辑','Production support / editing','Premiere Pro · Camera','#071012','repeating-linear-gradient(90deg,transparent 0 42px,rgba(53,255,181,.28) 43px 44px)'],
['MMD 渲染实验','MMD Rendering Study','2023–25','MOV-04','灯光 / 镜头 / 渲染','Lighting / camera / rendering','MMD · After Effects','#09070f','radial-gradient(circle at 55% 45%,#a229bc 0 5%,transparent 20%),linear-gradient(130deg,transparent 10%,rgba(34,91,255,.42) 42%,transparent 60%)'],
['短视频剪辑合集','Short-form Editing Reel','2024','MOV-05','选题 / 剪辑 / 发布','Editorial / editing / publishing','Premiere Pro · Douyin','#080a0d','linear-gradient(90deg,transparent 0 20%,rgba(255,41,70,.78) 20% 24%,transparent 24% 55%,rgba(31,221,237,.68) 55% 59%,transparent 59%)']
].map(x=>({title:[x[0],x[1]],year:x[2],code:x[3],role:[x[4],x[5]],tools:x[6],bg:x[7],pattern:x[8],desc:['项目详情将在替换真实视频后补充。','Detailed case-study text will be added with the final video.'],tags:['Motion','Editing','Story']}));
const projects={dialect:{title:['中国方言声学地图','Dialect Acoustic Atlas'],year:'2026',code:'DATA-01',role:['独立研究者','Independent researcher'],tools:'Python · Wav2Vec 2.0 · UMAP · Plotly',desc:['收集并清洗100余条中国方言语音，完成声学嵌入、距离计算、聚类和地理对照，并制作交互式数字方言地图。','A study of 100+ Chinese dialect samples using acoustic embeddings, clustering and geospatial comparison, resulting in an interactive dialect atlas.'],tags:['Audio embeddings','Clustering','Geospatial','Critical AI'],bg:'#d4d6d8',pattern:'repeating-radial-gradient(circle at 48% 48%,rgba(15,17,21,.14) 0 1px,transparent 1px 18px)'},jstor:{title:['JSTOR 中文用户研究','JSTOR Chinese UX Research'],year:'2025',code:'UX-02',role:['研究设计 / 访谈 / 编码 / 可视化','Research design / interviews / coding / visualisation'],tools:'Interviews · Usability Testing · Python',desc:['围绕中文文献检索与浏览体验开展访谈和可用性测试，并把编码结果转化为可视化洞察与优化建议。','Interviews and usability tests on Chinese-language discovery, translating coded findings into visual insights and recommendations.'],tags:['UX Research','Qualitative coding','Usability'],bg:'#e1d9c7',pattern:'linear-gradient(90deg,rgba(21,28,45,.86) 0 22%,transparent 22%),repeating-linear-gradient(0deg,transparent 0 33px,rgba(0,0,0,.13) 33px 34px)'},'data-news':{title:['预制菜数据新闻','Prepared Food Data Story'],year:'2024',code:'DATA-03',role:['数据收集 / 可视化 / 网页实现','Data collection / visualisation / web build'],tools:'Excel · Python · HTML/CSS',desc:['从产业趋势、消费者态度与政策环境展开数据叙事，项目获陕西赛区二等奖。','A data story spanning industry trends, consumer attitudes and policy, awarded second prize in the Shaanxi division.'],tags:['Data journalism','Web','Award'],bg:'#d7d0c4',pattern:'conic-gradient(from -20deg at 55% 48%,#e84c2b 0 11%,transparent 11% 25%,#243c70 25% 38%,transparent 38% 60%,#e5b546 60% 72%,transparent 72%)'}};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];

function star(){const host=$('#star-stage'),scene=new THREE.Scene(),cam=new THREE.PerspectiveCamera(34,1,.1,100),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});cam.position.z=8.5;renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.appendChild(renderer.domElement);const shape=new THREE.Shape();for(let i=0;i<20;i++){const a=i/20*Math.PI*2-Math.PI/2,r=i%2? .92:2.35,x=Math.cos(a)*r,y=Math.sin(a)*r;i?shape.lineTo(x,y):shape.moveTo(x,y)}shape.closePath();const geo=new THREE.ExtrudeGeometry(shape,{depth:.42,bevelEnabled:true,bevelSegments:5,bevelSize:.17,bevelThickness:.15});geo.center();const mesh=new THREE.Mesh(geo,new THREE.MeshPhysicalMaterial({color:0xbfc3c9,metalness:.92,roughness:.16,clearcoat:1}));mesh.rotation.set(-.22,.36,-.08);scene.add(mesh);scene.add(new THREE.AmbientLight(0xffffff,1.7));let l=new THREE.DirectionalLight(0xffffff,4.8);l.position.set(-4,6,7);scene.add(l);l=new THREE.DirectionalLight(0x8da4c9,3.6);l.position.set(5,-2,2);scene.add(l);let px=0,py=0;addEventListener('pointermove',e=>{px=(e.clientX/innerWidth-.5)*.28;py=(e.clientY/innerHeight-.5)*.18});function resize(){const r=host.getBoundingClientRect();renderer.setSize(r.width,r.height,false);cam.aspect=r.width/r.height;cam.updateProjectionMatrix()}resize();addEventListener('resize',resize);function loop(){const ty=state.dataMode?Math.PI+.35:.36;mesh.rotation.y+=(ty+px-mesh.rotation.y)*.04;mesh.rotation.x+=(-.22+py-mesh.rotation.x)*.04;mesh.rotation.z+=state.dataMode?-.0015:.0007;renderer.render(scene,cam);requestAnimationFrame(loop)}loop()}
function lang(v){state.lang=v;$$('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(T[v][k])el.innerHTML=T[v][k]});$('.lang-cn').classList.toggle('is-active',v==='zh');$('.lang-en').classList.toggle('is-active',v==='en');renderAll()}
function scene(v){state.scene=v;state.dataMode=false;$('.scene-home').classList.remove('data-mode');$$('.scene').forEach(x=>x.classList.toggle('is-visible',x.dataset.scene===v));history.replaceState(null,'',v==='home'?location.pathname:'#'+v)}
function render(type,items){const view=$(`[data-gallery="${type}"]`),track=$('.gallery-track',view);track.innerHTML='';items.forEach((item,i)=>{const off=i-state.galleries[type],card=document.createElement('article');card.className='gallery-card';card.style.setProperty('--offset',off);card.style.setProperty('--abs-offset',Math.abs(off));card.style.setProperty('--opacity',Math.max(.18,1-Math.abs(off)*.16));card.innerHTML=`<div class="gallery-art" data-code="${item.code}" style="--card-bg:${item.bg};--card-pattern:${item.pattern}"><div class="card-copy"><b>${item.title[state.lang==='zh'?0:1]}</b><span>${item.year}</span></div></div>`;card.onclick=()=>open(item);track.appendChild(card)});const wrap=view.closest('.gallery-scene');$('.gallery-current',wrap).textContent=String(state.galleries[type]+1).padStart(2,'0');$('.gallery-total',wrap).textContent=String(items.length).padStart(2,'0')}
function renderAll(){render('poster',posters);render('video',videos)}function move(type,d){const a=type==='poster'?posters:videos;state.galleries[type]=(state.galleries[type]+d+a.length)%a.length;render(type,a)}
function open(item){const d=$('.project-dialog'),i=state.lang==='zh'?0:1;$('.dialog-kicker').textContent=item.code;$('.dialog-content h3').textContent=item.title[i];$('.dialog-description').textContent=item.desc[i];$('.dialog-role').textContent=item.role[i];$('.dialog-tools').textContent=item.tools;$('.dialog-year').textContent=item.year;$('.dialog-tags').innerHTML=item.tags.map(x=>`<span>${x}</span>`).join('');$('.dialog-visual').style.setProperty('--dialog-bg',item.bg);$('.dialog-visual').style.setProperty('--dialog-pattern',item.pattern);d.showModal()}
$$('[data-action="home"]').forEach(x=>x.onclick=()=>scene('home'));$$('[data-chapter]').forEach(x=>x.onclick=()=>{const c=x.dataset.chapter;if(c==='data'){state.dataMode=true;$('.scene-home').classList.add('data-mode')}else scene(c)});$$('[data-project]').forEach(x=>x.onclick=()=>open(projects[x.dataset.project]));$$('[data-gallery-prev]').forEach(x=>x.onclick=()=>move(x.dataset.galleryPrev,-1));$$('[data-gallery-next]').forEach(x=>x.onclick=()=>move(x.dataset.galleryNext,1));$('.lang-toggle').onclick=()=>lang(state.lang==='zh'?'en':'zh');$('.dialog-close').onclick=()=>$('.project-dialog').close();$('.project-dialog').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.close()};$('.contact-trigger').onclick=()=>$('.contact-wrap').classList.toggle('is-open');$$('[data-gallery]').forEach(v=>{let sx;v.onpointerdown=e=>sx=e.clientX;v.onpointerup=e=>{if(Math.abs(e.clientX-sx)>45)move(v.dataset.gallery,e.clientX>sx?-1:1)};v.addEventListener('wheel',e=>{e.preventDefault();move(v.dataset.gallery,(e.deltaY||e.deltaX)>0?1:-1)},{passive:false})});const dot=$('.cursor-dot');addEventListener('pointermove',e=>{dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px'});$$('button,a,.gallery-card').forEach(x=>{x.onmouseenter=()=>dot.classList.add('is-hover');x.onmouseleave=()=>dot.classList.remove('is-hover')});
star();renderAll();const h=location.hash.slice(1);if(['poster','video','about'].includes(h))scene(h);